"""insert data admin in User

Revision ID: 204710bc6a3e
Revises: bc6f3ee3e062
Create Date: 2024-05-12 18:18:39.724589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '204710bc6a3e'
down_revision = 'bc6f3ee3e062'
branch_labels = None
depends_on = None

from api.models import User ,Base, engine # Assuming User model is defined in api.models
from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
session = Session()


def upgrade():
    
    user_data = {
        'id': 'd00ebeb6-81d2-4ca0-9430-ee8b80aebeca',
        'email': 'admin@admin.com',
        'password': 'scrypt:32768:8:1$z2trXDIlYeDAH2PT$7435443d88549c23daff9ad6a2ad4cdbb7fe4ad950b094e6b4c0063b8d96a04ca7800b15acf66906503e00eab6bb0ae7e7c5253aae71557e245c852bc292ef7f',
        'role_id': 1
    }

    user = User(**user_data)
    session.add(user)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('cam_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cam_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('launch_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('send_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temp_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smtp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('cam_id', name='campaign_pkey')
    )
    op.create_table('permission',
    sa.Column('perm_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('perm_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('perm_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('perm_id', name='permission_pkey')
    )
    op.create_table('grouptarget',
    sa.Column('groupid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('targetid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['groups.id'], name='grouptarget_groupid_fkey'),
    sa.ForeignKeyConstraint(['targetid'], ['target.id'], name='grouptarget_targetid_fkey')
    )
    op.create_table('page',
    sa.Column('page_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('page_id', name='page_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=170), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='users_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_table('template',
    sa.Column('temp_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('temp_subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('temp_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temp_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('temp_id', name='template_pkey')
    )
    op.create_table('role',
    sa.Column('role_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', name='role_pkey')
    )
    op.create_table('result',
    sa.Column('rid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rid', name='result_pkey')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groupname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('camp_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    op.create_table('smtp',
    sa.Column('smtp_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('host', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('from_address', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ignore_cert_errors', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('smtp_id', name='smtp_pkey')
    )
    op.create_table('target',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_addr', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('sess_id', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='target_pkey')
    )
    # ### end Alembic commands ###
